### ISSUE TITLE
Exported games are unable to find actions.json

### ISSUE THREAD

**Issue by beniwtv** [GodotVR/godot_openvr#95]
Right now we have an issue in Godot (https://github.com/godotengine/godot/issues/36781) that prevents exported games with OpenVR from working, as SteamVR is unable to find **actions.json**.

The reason is that currently the function we use in the plugin uses **ProjectSettings.globalize_path()** to point SteamVR to the actions file. But this function returns a relative path in exported games, which SteamVR is unable to handle.

As a temporary workaround, one can set the path manually in the **OpenVRConfig** object to something like:

`OpenVRConfig.set_action_json_path(OS.get_executable_path() + "addons/godot_openvr/actions/actions.json")`

**Note:** Change path as needed, this is just for the default location of the JSON file inside the addon (which we recommend copying to another directory and adapting it as per https://github.com/GodotVR/godot-openvr-asset/wiki/OpenVR-actions).

**Note 2:** This will probably not work on systems like Android / iOS, adapt as needed (but I think there is no OpenVR there in any case (?)).

**Comment by BastiaanOlij** [comment]
Cheers Ben, as we discuss we'll have a look at how the core team reacts on how this is supposed to work before we change anything on our side, especially with the viable workaround in just setting the path directly on our config object.

Bit of a nuisance this. I don't test the exports often enough.

**Comment by BastiaanOlij** [comment]
I really need to get back onto this, we learned some more about this but I haven't had the time to implement it.

The much bigger problem is that when exporting our game our json files get included in our gamepack file, out of reach of OpenVR.

My suggestion is that we do away with the setting all together. We should look for the config files in 3 fixed locations in order:
1) check for an actions folder alongside the executable and use those (this is for release)
2) else check for an actions folder in the root of our project (for custom files)
3) if that doesn't exists use the actions folder in our plugin (our backwards compatible defaults)

Then we implement an [EditorExportPlugin](https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html) class that will grab either the json files in location 2 or 3 and export them to an actions folder alongside the executable (so end result is 1)

**Comment by ChristophHaag** [comment]
For xrdesktop we compile the action and bindings manifests into the application as a resource and when running, the manifests are written to a file at the standard cache path, ${XDG_CACHE_HOME} on linux.

Though this poses the question whether to overwrite the manifest when the user edited it (we say yes because the SteamVR binding ui stores altered bindings independently of the bindings manifest).

**Comment by lyuma** [comment]
We successfully got things working on export builds. I'm going to document the workaround we used, though hopefully it will cease to be necessary once fixed upstream:

```gdscript
if ProjectSettings.globalize_path("res://") == "":
    openvr_config.action_json_path = OS.get_executable_path().get_base_dir() + "/" + action_json_filename
else:
    openvr_config.action_json_path = "res://addons/vr_manager/openvr/" + action_json_filename
```

Note: The above solution checks directly for the cause of the issue: if globalize_path fails to produce a global path, we use the base directory of the executable path.

I recommend using globalize_path here instead of checking for "standalone" or "release" platforms, as platform checks fail if you export a debug build; or if you test an export build with a editor/tools build of the engine.

It's also your responsibility to ensure that .json bindings and actions files are actually exported. Our build system takes the `actions` directory from (in our case) `addons/vr_manager/openvr/actions` and copies it to `EXPORT_DIR/actions`, for example. This seemed to me to be far less error-prone than listing json files in every export configuration, but ymmv

Hope this helps others who run into this until fixed upstream.

**Comment by BastiaanOlij** [comment]
Ok I've got this working so that during development it looks for the action files in a folder called `actions` in the root of your project first, and if it doesn't exist it will use the default action files it will look for the folder in the `godot_openvr` addons folder.

When exporting your project it will export those files alongside your exe.

When running in runtime it will use the files alongside the exe (this is always the first place it looks even in development)

See #105

**Comment by croxis** [comment]
This bug reared its head for me with 1.1.0 of godot-openvr and godot 3.3.2, windows 10 steam version. I had to copy the actions folder to my exported exe folder to get it working.

**Comment by BastiaanOlij** [comment]
If I recall correctly you need to enable the plugin in the plugins tab of your project settings for the export to copy over the files for you. Could remember wrong though.
